### PR TITLE
Testing codecov PR integration

### PR DESCRIPTION
**Pull request by ezzatron**

### CODE REVIEW

**Comment by stevepeak** [comment]
- The patch status failed to process due because the diff was to large to process between 52475ea...a47b945
- Note: removing lines that were covered can actually increase overall coverage.

In this case however I'm not sure what to say. The complexity of this pull request if throwing off a lot of measurements. Even Github cannot show the entire diff because its to large... IMO if you would like to test how Codecov works, I suggest not doing it by simply removing files. Remove the tests.

**Comment by ezzatron** [comment]
@stevepeak I see, that makes sense.

Just to clarify, the removed files *are* tests. I didn't remove anything else. But I can understand how such a large diff would cause issues.

Strangely though, if you look at the Codecov status check (the last commit for example), it seems to know the total coverage percentage went from 100% to 75.55%, but still returns a passing status. That seems like a bug.

**Comment by stevepeak** [comment]
>  100% to 75.55%, but still returns a passing status. That seems like a bug.

Certainly I agree. We do offset the coverage to take in to account removing lines that were once covered, but that should not account for this large of issue. 

Unfortunately it would take me to long to review this large of diff to find a bug. If we had a controlled case, or at the least a smaller case, that expressed this issue then I would review it. Thousands of customers rely on our accuracy and no reports of it being inaccurate are surfacing at the moment.

Thanks!

**Comment by ezzatron** [comment]
@stevepeak No worries, thanks for looking into it :)

**Pull request closed without merging**
